### ISSUE TITLE
Making NewPool Variadic 

### ISSUE THREAD

**Issue by zabawaba99** [CloudCom/fireload#3]
Would it be better to pass in the Namespaces as varargs instead of a slice?

**Comment by MrGossett** [comment]
Better in terms of usability? Maybe.

IMHO, implementers will most likely build up a `[]Namespace` before passing it to `NewPool`, so having a single slice parameter would be easiest (`NewPool(mySlice)`). If we use varargs, they would have to do `NewPool(mySlice...)`.

However, implementers that just want to instantiate an empty pool would find varargs convenient because they could just do `NewPool()`.

Something we don't have yet, which I think would be useful, is a pair of `func`s to add and drop namespaces from an existing pool. Some thing like this:

```
func (p *Pool) Add(Namespace) error
func (p *Pool) Drop(Namespace) error
```

If we add these, then I would definitely go for varargs in `NewPool`
